name = "ai-sermon-helper-worker"
main = "worker/index.mjs"
compatibility_date = "2024-05-20"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "ai-sermon-helper-db"
database_id = "bd4069ce-2e4d-4f63-9512-ccafd635c211"
